JMS/Controllers/Manufacturers/ManufacturerGridController.cs
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using JMS.Models;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using System.Web.Routing;
using System.Data.Entity;
using System;
using System.Collections.Generic;
using System.IO;
using System.Text;

namespace JMS.Controllers
{
    [Authorize]
    public class ManufacturerGridController : GridController<Manufacturer, ManufacturerViewModel>
    {

        public ManufacturerGridController()
            : base(new ManufacturerRepository(), new ManufacturerMapper())
        {

        }


        protected override void Initialize(RequestContext requestContext)
        {
            base.Initialize(requestContext);
            this.CheckSubscription();

            //if (ViewBag.ViewCRM == false)
            //   Response.Redirect("/");
        }


        [AcceptVerbs(HttpVerbs.Post)]
        public JsonResult Read([DataSourceRequest]DataSourceRequest request, string filterText)
        {
            //User passed parameters oo filter results
            var list = _repo.Read().Where(
                         cls => 
                         (
                             (cls.Name.ToLower().Contains(filterText.ToLower())
                             ) || filterText.Equals("") || filterText.Equals(null)
                         )
                         //&& (cls.SupplierProducts.Where(t => t.SupplierTag.ID.ToString() == tag).Count() > 0 || tag == "" || tag == null)
                         && cls.Deleted == false  //Make sure only non-deleted suppliers are returned
                     );

            list = ApplyQueryFiltersSort(request, list, "RefID");

            var results = list.Skip(request.PageSize * (request.Page - 1)).Take(request.PageSize).ToList().Select(clt => _mapper.MapToViewModel(clt));
            DataSourceResult result = new DataSourceResult { Data = results.ToList(), Total = list.Count() };
            return Json(result);

        }


        public virtual JsonResult ReadDeleted([DataSourceRequest] DataSourceRequest request)
        {
            var list = _repo.Read().Where(p => p.Deleted == true);
            var viewModels = list.OrderBy(c => c.Name).ToList().Select(s => _mapper.MapToViewModel(s));

            return Json(viewModels.ToDataSourceResult(request));
        }


        public override JsonResult Read([DataSourceRequest] DataSourceRequest request)
        {
            return Json(new List<SupplierViewModel>().ToDataSourceResult(request));
        }



        [AcceptVerbs(HttpVerbs.Post)]
        public virtual JsonResult Delete([DataSourceRequest] DataSourceRequest request, ProductViewModel viewModel)
        {
            
            var model = _repo.Find(Guid.Parse(viewModel.ID));
            model.Deleted = true;
            _repo.Update(model, new string[] { "Deleted" });

           
            return Json(new[] { viewModel }.ToDataSourceResult(request, ModelState));
        }


        // POST: /Delete Suppliers
        [HttpPost]
        public ActionResult _DeleteManufacturers(string IDs)
        {
            //IDs are passed as a string e.g.  1,2,4,5,6,7,8            
            foreach (string i in IDs.Split(',').ToArray())
            {
                try
                {
                    var model = _repo.Find(Guid.Parse(i));
                    model.Deleted = true;
                    _repo.Update(model, new string[] { "Deleted" });

                }
                catch { }
            }
            return Json("Success");
        }

    }
    
}

JMS/Controllers/Manufacturers/ManufacturersController.cs
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using JMS.Models;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using System.Web.Routing;
using System.Data.Entity;
using System;
using System.Collections.Generic;
using System.IO;
using System.Text;

namespace JMS.Controllers
{
    [Authorize]
    public class ManufacturersController : EntityController<Manufacturer, ManufacturerViewModel>
    {
      
        public ManufacturersController()
            : base(new ManufacturerRepository(), new ManufacturerMapper())
        {

        }


        protected override void Initialize(RequestContext requestContext)
        {
            base.Initialize(requestContext);
            this.CheckSubscription();

            if (ViewBag.ViewCRM == false)
               Response.Redirect("/");
        }

        

        // GET: Suppliers
        public ActionResult Index(string ID)
        {
            if (ID != null) ViewBag.SupplierID = ID;

            ViewBag.CurrentUserID = CurrentUser.Id;
            ViewBag.CurrentUserEmail = CurrentUser.Email;

            return View();
        }

        public ActionResult Deleted()
        {
            if (ViewBag.DeleteCRM == false)
                Response.Redirect("/");

            return View();
        }



        #region Edit Manufacturer Panel

        // GET: /New Manufacturer
        public ActionResult _NewManufacturer()
        {
            var manufacturer = new ManufacturerRepository().Read().OrderByDescending(x => x.RefID).FirstOrDefault();
            var refID = manufacturer != null ? manufacturer.RefID + 1 : 1;

            return PartialView(new ManufacturerViewModel() { RefID = refID });             
        }


        // POST: /New Manufacturer
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult _NewManufacturer(ManufacturerViewModel viewModel)
        {
            if (viewModel == null) return RedirectToAction("Index");

            //Check to see if model is valid
            if (!ModelState.IsValid)
            {
                return PartialView(viewModel);
            }

            var model = _mapper.MapToModel(viewModel);
            _repo.Create(model);


            //Log Activity
            //AddLog(model.ID.ToString(), string.Format("{{{0}}} created.", 0), CurrentUser);
                
            return Json(new { ID = model.ID });                
           
        }



        // GET: /Edit Supplier
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")] 
        public ActionResult _EditManufacturer(string ID)
        {
            try
            {
                //Make sure the supplier being returned belongs to the user of the user
                Manufacturer clt =  _repo.Read().Where(o => o.ID.ToString() == ID).First();
                ManufacturerViewModel model = _mapper.MapToViewModel(clt);

                ViewBag.CurrentUserID = CurrentUser.Id;
                ViewBag.CurrentUserEmail = CurrentUser.Email;
                return PartialView(model);
            }
            catch {
                return PartialView("_NewSupplier", new ManufacturerViewModel());
            }

        }


        // POST: /Edit Supplier
        [HttpPost]
        [ValidateAntiForgeryToken]
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")] 
        public ActionResult _EditManufacturerDetails(ManufacturerViewModel viewModel)
        {
            if (viewModel == null) return RedirectToAction("Index");

            //Check to see if model is valid
            if (!ModelState.IsValid)
            {
                return PartialView(viewModel);
            }

            var edit = _repo.Find(Guid.Parse(viewModel.ID));
            _mapper.MapToModel(viewModel, edit);
            _repo.Update(edit);


            ViewBag.CurrentUserID = CurrentUser.Id;
            ViewBag.CurrentUserEmail = CurrentUser.Email;
            ViewBag.Saved = true; //Return a viewbag variable. Used to show message in front-end html.
            return PartialView(viewModel);
            
        }

        #endregion

        /*
        public ActionResult _AddManufacturerPopup(string OrderID, string Type)
        {
            ViewBag.OrderID = OrderID;
            ViewBag.Type = Type;
            return PartialView(new ManufacturerViewModel { });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult _AddManufacturerPopup(ManufacturerViewModel viewModel, string OrderID, string Type)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.OrderID = OrderID;
                ViewBag.Type = Type;
                return PartialView(viewModel);
            }

            var supplier = _mapper.MapToModel(viewModel);
            supplier.CompanyID = CurrentUser.CompanyID;
            _repo.Create(supplier);

            if (Type == "PurchaseOrder")
            {
                var oRepo = new PurchaseOrderRepository();
                var model = oRepo.Find(Guid.Parse(OrderID));
                model.SupplierID = supplier.ID;
                model.LastUpdated = DateTime.Now;
                oRepo.Update(model, new string[] { "SupplierID", "LastUpdated" });
            }
           

            //Log Activity
            AddLog(viewModel.ID, string.Format("{{{0}}} details updated.", 0), CurrentUser);


            return JavaScript("OnEditSupplierContactAddress();");
        }


        public ActionResult _EditManufacturerPopup(string OrderID, string Type)
        {
            ViewBag.OrderID = OrderID;
            ViewBag.Type = Type;

            try
            {
                Manufacturer supplier = null;

                if (Type == "PurchaseOrder")
                {
                    var oRepo = new PurchaseOrderRepository();
                    var model = oRepo.Find(Guid.Parse(OrderID));
                    supplier = _repo.Find(model.SupplierID);
                }

                var viewModel = _mapper.MapToViewModel(supplier);
                return PartialView(viewModel);
            }
            catch
            {
                return RedirectToAction("_AddSupplierPopup", new { OrderID = OrderID, Type = Type });
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult _EditManufacturerPopup(ManufacturerViewModel viewModel, string OrderID, string Type)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.OrderID = OrderID;
                ViewBag.Type = Type;
                return PartialView(viewModel);
            }

            var customer = _repo.Find(Guid.Parse(viewModel.ID));
            _mapper.MapToModel(viewModel, customer);
            _repo.Update(customer);

            //Log Activity
            AddLog(OrderID, string.Format("{{{0}}} supplier details updated.", 0), CurrentUser);


            return JavaScript("OnEditSupplierContactAddress();");
        }

        */

    }
    
}

JMS/Views/Manufacturers/Index.cshtml
@{
    ViewBag.Title = "Manufacturer";
}

<div class="container">
    <div class="row">
        <div class="col-sm-6">
            <h1>Manufacturer</h1>
        </div>
        <div class="col-sm-6">
            <br />
        </div>
        <div class="col-sm-12">
            <br />
        </div>
        <div class="col-xs-6">
            @if (!User.IsInRole("Viewer"))
            {
                <a class="btn btn-inverse" onclick="NewManufacturer()"><span class="glyphicon glyphicon-home"></span>&nbsp;New Manufacturer</a>
            }            
        </div>
        <div class="col-xs-2">
            <br />
        </div>
        
        <div class="col-xs-4">
            <div class="input-group">
                @Html.TextBox("TB_ManufacturerFilter", null, new { @class = "form-control", @style = "max-width:none", @placeholder = "Search by Name" })
                <span class="input-group-btn">
                    <a class="btn btn-default" onclick="Refresh()"><span class="glyphicon glyphicon-search"></span></a>
                </span>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <hr />
        </div>
        <div id="divPager" class="col-sm-12">
             <div class="form-group" role="group" aria-label="...">
                <a class="btn btn-sm btn-default" onclick="Refresh()"><span class="glyphicon glyphicon-refresh" ></span>&nbsp; Refresh</a>&nbsp;
                 @if (ViewBag.EditCRM)
                 {
                    //<a class="btn btn-sm btn-default" onclick="Edit()"><span class="glyphicon glyphicon-edit"></span>&nbsp; Edit</a>
                 } 
            </div>
        </div>

        @*@if (ViewBag.EditCRM)
        {
            <div id="divEdit" class="col-sm-12" style="display:none">
                <div class="form-group" role="group" aria-label="...">
                    <a class="btn btn-sm btn-default" onclick="SelectAll()"><span class="glyphicon glyphicon-check"></span>&nbsp; Select All</a>&nbsp;
                    <a class="btn btn-sm btn-default" onclick="DeleteSelected()"><span class="glyphicon glyphicon-trash"></span>&nbsp; Delete Selected</a>&nbsp;
                    <a class="btn btn-sm btn-default" onclick="DoneEdit()"><span class="glyphicon glyphicon-ok"></span>&nbsp; Done</a>&nbsp;
                </div>
            </div>
        }*@
        <div class="col-sm-12">
            @(Html.Kendo().Grid<JMS.Models.ManufacturerViewModel>()
                .Name("GridManufacturers")
                .HtmlAttributes(new { style = "min-width: 500px" })
                .Pageable(p => p.PageSizes(new[] { 50, 100, 200 }).Messages(m => m.Display("{0} - {1} of {2} Manufacturer").Empty("No Manufacturer Found")))
                .Columns(columns =>
                {
                    columns.Template(@<text></text>).ClientTemplate("<input type='checkbox' value='#=ID#' name='chk_grid'>").Width("1%").Hidden();
                    //columns.Bound(u => u.RefID).Title("ID").Width("1%");
                    columns.Bound(u => u.Name).Title("Name").ClientTemplate("<a href='\\#' onclick='EditManufacturer(\"#=ID#\"); return false;'><strong>#=Name#</strong></a>");
                    columns.Template(@<text></text>).ClientTemplate("<a href='\\#' onclick='EditManufacturer(\"#=ID#\"); return false;'><span class='glyphicon glyphicon-edit glyphicon-btn'/></a>").Width("1%");
                    columns.Command(command =>
                    {
                        command.Destroy().Text("<span class='glyphicon glyphicon-trash glyphicon-btn' title='Delete' />");
                    }).Visible(!User.IsInRole("Viewer")).Width("1%");
                })
                .Sortable()
                .Editable(editable => editable.ConfirmDelete("Are you sure you want to delete this Manufacturer?"))
                .DataSource(dataSource => dataSource
                    .Ajax()
                    .Model(model =>
                    {
                        model.Id(t => t.ID);
                    })
                    .Read(read => read.Action("Read", "ManufacturerGrid").Data("GetSearchInfo")).PageSize(50)
                    .Update(update => update.Action("Update", "ManufacturerGrid"))
                    .Destroy(destory => destory.Action("Destroy", "ManufacturerGrid"))
                    .Events(events => events.Error("KendoGridErrorHandler"))
                )
                .Events(events => events.DataBound("KendoGridDatabound"))
            )
        </div>        
    </div>
</div>


<a id="Button_Close_Content" class="btn btn-background" onclick="HideViews()" style="z-index:1105; display:none;"></a>

<div id="SlideContent_EditManufacturer" class="panel panel-default" style="z-index: 1120; position: fixed; overflow-y:scroll; margin: 0; top: 0; bottom:0; right: 0%; min-height: 100%; width: 0; max-width: 1000px; display: none;">
    <div class="panel-body" style="margin-top: 10px;">
        <div id="EditManufacturer_Body"></div>
    </div>
</div>

<script>

    @if (!string.IsNullOrEmpty(ViewBag.ManufacturerID))
    {
        <text>
    EditManufacturer('@ViewBag.ManufacturerID');
    </text>
    }

    function Refresh() {
        var grid = $("#GridManufacturers").data("kendoGrid");
        //if (grid.dataSource.page() != 1) {
        //    grid.dataSource.page(1);
        //}
        grid.dataSource.read();
    }

    function RefreshContacts() {
        var grid = $("#GridContactsSearch").data("kendoGrid");
        //if (grid.dataSource.page() != 1) {
        //    grid.dataSource.page(1);
        //}
        grid.dataSource.read();
    }

    function GetSearchInfo() {
        return {
            filterText: $('#TB_ManufacturerFilter').val(),
        }
    }

    function Edit() {
        var grid = $("#GridManufacturers").data("kendoGrid");
        if (grid.dataSource.total() > 0) {
            $('#divPager').hide();
            $('#divEdit').show();
            grid.showColumn(0);
        }
    }

    function DoneEdit() {
        var grid = $("#GridManufacturers").data("kendoGrid");
        $('#divPager').show();
        $('#divEdit').hide();
        grid.hideColumn(0);
    }

    function SelectAll() {
        if ($("input[name=chk_grid]:checkbox:checked").get().length > 0) {
            $("input[name=chk_grid]").map(function () { return this.checked = false; })
        }
        else {
            $("input[name=chk_grid]").map(function () { return this.checked = true; })
        }
    }


    $("#TB_ManufacturerFilter").keyup(function (e) {
        //if (e.keyCode == 13) {
            Refresh();
        //}
    });

    $("#TB_ContactFilter").keyup(function (e) {
        //if (e.keyCode == 13) {
            RefreshContacts();
        //}
    });


    //Below the following functions are used the show/hide the content panels.
    function NewManufacturer() {
        $("#EditManufacturer_Body").load("@Url.Action("_NewManufacturer", "Manufacturers")");

        $("#SlideContent_EditManufacturer").animate({ width: '90%' }, { queue: false, duration: 300 });
        $("#SlideContent_EditManufacturer").fadeIn();
        $("#Button_Close_Content").fadeIn();
    }

    function EditManufacturer(id) {
        var url = '@Url.Action("_EditManufacturer", "Manufacturers")' + '?ID=' + id;
        $("#EditManufacturer_Body").load(url);

        $("#SlideContent_EditManufacturerTypes").fadeOut();
        $("#SlideContent_SearchContacts").fadeOut();

        $("#SlideContent_EditManufacturer").animate({ width: '90%' }, { queue: false, duration: 300 });
        $("#SlideContent_EditManufacturer").fadeIn();
        $("#Button_Close_Content").fadeIn();
    }

    function CreatedManufacturer(id) {
        var url = '@Url.Action("_EditManufacturer", "Manufacturers")' + '?ID=' + id;
        $("#EditManufacturer_Body").load(url);
    }

    @if (ViewBag.EditCRM)
    {
        <text>

            function DeleteManufacturer(id) {
                if (confirm("Are you sure you want to delete this organisation?")) {
                    $.ajax({
                        url: '@Url.Action("_DeleteManufacturer", "Manufacturers")',
                        type: 'POST',
                        data: { "ID": id },
                        dataType: "json",
                        success: function (data) { Refresh(); }
                    });
                }
            }

            function DeleteSelected() {
                if (confirm("Are you sure you want to delete these organisations?")) {

                    var ids = $("input[name=chk_grid]:checkbox:checked").map(function () { return this.value; }).get().join();

                    $.ajax({
                        url: '@Url.Action("_DeleteManufacturers", "ManufacturerGrid")',
                        type: 'POST',
                        data: { "IDs": ids },
                        dataType: "json",
                        success: function (data) { Refresh(); }
                    });
                }
            }
        </text>
    }

    function EditManufacturerTypes() {

        $("#SlideContent_EditManufacturerTypes").animate({ width: '90%' }, { queue: false, duration: 300 });
        $("#SlideContent_EditManufacturerTypes").fadeIn();
        $("#Button_Close_Content").fadeIn();

        var grid = $("#GridAllLogs").data("kendoGrid");
        grid.dataSource.read();
    }


    function SearchContacts() {
        $("#SlideContent_SearchContacts").animate({ width: '90%' }, { queue: false, duration: 300 });
        $("#SlideContent_SearchContacts").fadeIn();
        $("#Button_Close_Content").fadeIn();

        var grid = $("#GridContactsSearch").data("kendoGrid");
        grid.dataSource.read();
    }

    function HideViews() {
        $("#SlideContent_EditManufacturer").animate({ width: '0%' }, { queue: false, duration: 300 });
        $("#SlideContent_EditManufacturerTypes").animate({ width: '0%' }, { queue: false, duration: 300 });
        $("#SlideContent_SearchContacts").animate({ width: '0%' }, { queue: false, duration: 300 });
        setTimeout(function () {
            $("#SlideContent_EditManufacturer").fadeOut();
            $("#SlideContent_EditManufacturerTypes").fadeOut();
            $("#SlideContent_SearchContacts").fadeOut();
            $("#Button_Close_Content").fadeOut();
        }, 300);

    }

</script>

JMS/Views/Manufacturers/_EditManufacturer.cshtml
@model JMS.Models.ManufacturerViewModel

@Html.Partial("_EditManufacturerDetails", Model)

<div class="row">
    <div class="col-sm-12">
        <br />
        @(Html.Kendo().TabStrip().Scrollable(false)
        .Name("Manufacturer_Tabstrip")
        .Items(tabstrip =>
        {
            //tabstrip.Add().Text("Contacts").Content(@Html.Partial("_ContactsTab", Model).ToHtmlString()).Selected(true);
            //tabstrip.Add().Text("Purchase Orders").Content(@Html.Partial("_PurchaseOrdersTab", Model).ToHtmlString()).Selected(false);
            /*
            if (Model.IsSupplier)
            {
                tabstrip.Add().Text("Supplier Categories").Content(@Html.Partial("_CategoriesTab", Model).ToHtmlString()).Selected(false);
            }
            */
        }))
    </div>
</div>

JMS/Views/Manufacturers/_EditManufacturerDetails.cshtml
@model JMS.Models.ManufacturerViewModel

<div id="divEditManufacturer">
     <script> $("divEditManufacturer").submit(function (e) { e.preventDefault(e); }); </script>
    
    <div class="row form-table" style="margin-left:5px; margin-right:5px;">
        <div class="col-sm-12">
            @using (Ajax.BeginForm("_EditManufacturerDetails", "Manufacturer", new AjaxOptions { UpdateTargetId = "divEditManufacturer" }, FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                @Html.HiddenFor(model => model.ID)
                @Html.HiddenFor(model => model.Deleted)
                @Html.HiddenFor(model => model.RefID)
                <div id="div_Body" class="row">
                    <div class="col-xs-9">
                        <h2>Edit Manufacturer</h2>
                    </div>
                    <div class="col-xs-3">
                        <br />
                        <div style="float:right;">
                            @if (!User.IsInRole("Viewer"))
                            {
                                <text>
                                <input type="submit" value="Save Changes" class="btn btn-sm btn-inverse">&nbsp;
                                </text>
                            }
                            <a class="btn btn-sm btn-default" onclick="HideViews()"><span class="glyphicon glyphicon-remove"></span>&nbsp;Close</a>
                            @if (ViewBag.Saved != null)
                            {
                                <label class="l_Saved"><strong>Details Saved!</strong></label>
                            }
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <br />
                    </div>
                    <div class="col-sm-4">
                        <table>
                            @*<tr>
                                <td style="width:80px;"><label>ID:</label></td>
                                <td>
                                    @Html.TextBoxFor(model => model.RefID, new { @class = "form-control", @placeholder = "ID", @style = "max-width:none; width:100%;" })
                                    @Html.ValidationMessageFor(model => model.RefID, "", new { @class = "text-danger" })
                                </td>
                            </tr>*@
                            <tr>
                                <td style="width:80px;"><label>Name:</label></td>
                                <td>
                                    @Html.TextBoxFor(model => model.Name, new { @class = "form-control", @placeholder = "Supplier Name", @style = "max-width:none; width:100%;" })
                                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                </td>
                            </tr>
                        </table>
                    </div>
                    @if (!User.IsInRole("Viewer"))
                    {
                    <div class="col-sm-12">
                        <br /><br />
                        <input type="submit" value="Save Changes" class="btn btn-inverse">&nbsp;
                        @if (ViewBag.Saved != null)
                        {
                            <label class="l_Saved"><strong>Details Saved!</strong></label>
                            <script>
                                Refresh();
                                setTimeout(function () { $(".l_Saved").fadeOut(); }, 2000);
                            </script>
                        }
                    </div>
                    }
                </div>
            }
        </div>
    </div>

</div>

JMS/Views/Manufacturers/_NewManufacturer.cshtml
@model JMS.Models.ManufacturerViewModel

<div id="divNewOrg" style="margin:15px;">

    @using (Ajax.BeginForm("_NewManufacturer", "Manufacturer", new AjaxOptions { UpdateTargetId = "divNewOrg", OnSuccess = "OnSuccess" }, FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        //@Html.ValidationSummary(false, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div id="div_Body"  class="row">
            <div class="col-xs-9">
                <h2>New Manufacturer</h2>
            </div>
            <div class="col-xs-3">
                <br />
                <div style="float:right;">
                    <input type="submit" value="Add Manufacturer" class="btn btn-sm btn-inverse">
                    <a class="btn btn-sm btn-default" onclick="HideViews()"><span class="glyphicon glyphicon-remove"></span>&nbsp;Close</a>
                </div>
            </div>
            <div class="col-sm-12">
                <br />
            </div>
            @Html.HiddenFor(model => model.RefID)
            <div class="col-sm-4">
                <table>
                    @*<tr>
                        <td style="width:80px;"><label>ID:</label></td>
                        <td>
                            @Html.TextBoxFor(model => model.RefID, new { @class = "form-control", @placeholder = "ID", @style = "max-width:none; width:100%;" })
                            @Html.ValidationMessageFor(model => model.RefID, "", new { @class = "text-danger" })
                        </td>
                    </tr>*@
                    <tr>
                        <td style="width:80px;"><label>Name:</label></td>
                        <td>
                            @Html.TextBoxFor(model => model.Name, new { @class = "form-control", @placeholder = "Manufacturer Name", @style = "max-width:none; width:100%;" })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </td>
                    </tr>
                </table>
            </div>
            <div class="col-sm-4">
                <br />
            </div>
            <div class="col-sm-12">
                <br /><br />
                <input type="submit" value="Add Manufacturer" class="btn btn-inverse">
            </div>
        </div>
    }

    <script>
        function OnSuccess(response) {
            //Call function from Index view
            Refresh();
            CreatedManufacturer(response["ID"]);
        }
    </script>

    <style>
        #div_Body table tr th, #div_Body table tr td {
            padding: 2px;
        }

        #div_Body table {
            width: 100%;
        }
    </style>

</div>