JMS/Controllers/Requestors/RequestorGridController.cs
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using JMS.Models;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using System.Web.Routing;
using System.Data.Entity;
using System;
using System.Collections.Generic;
using System.IO;
using System.Text;

namespace JMS.Controllers
{
    [Authorize]
    public class RequestorGridController : GridController<Requestor, RequestorViewModel>
    {

        public RequestorGridController()
            : base(new RequestorRepository(), new RequestorMapper())
        {

        }


        protected override void Initialize(RequestContext requestContext)
        {
            base.Initialize(requestContext);
            this.CheckSubscription();

            //if (ViewBag.ViewCRM == false)
            //   Response.Redirect("/");
        }


        [AcceptVerbs(HttpVerbs.Post)]
        public JsonResult Read([DataSourceRequest]DataSourceRequest request, string filterText)
        {
            //User passed parameters oo filter results
            var list = _repo.Read().Where(
                         cls => 
                         (
                             ((cls.FirstName.ToLower() + " " + cls.Surname.ToLower()).Contains(filterText.ToLower())
                             ) || filterText.Equals("") || filterText.Equals(null)
                         )
                     );

            list = ApplyQueryFiltersSort(request, list, "RefID");

            var results = list.Skip(request.PageSize * (request.Page - 1)).Take(request.PageSize).ToList().Select(clt => _mapper.MapToViewModel(clt));
            DataSourceResult result = new DataSourceResult { Data = results.ToList(), Total = list.Count() };
            return Json(result);

        }


        public virtual JsonResult ReadDeleted([DataSourceRequest] DataSourceRequest request)
        {
            var list = _repo.Read();
            var viewModels = list.OrderBy(c => c.Name).ToList().Select(s => _mapper.MapToViewModel(s));

            return Json(viewModels.ToDataSourceResult(request));
        }


        public override JsonResult Destroy(DataSourceRequest request, RequestorViewModel viewModel)
        {
            return base.Destroy(request, viewModel);
        }

    }
    
}

JMS/Controllers/Requestors/RequestorsController.cs
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using JMS.Models;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using System.Web.Routing;
using System.Data.Entity;
using System;
using System.Collections.Generic;
using System.IO;
using System.Text;

namespace JMS.Controllers
{
    [Authorize]
    public class RequestorsController : EntityController<Requestor, RequestorViewModel>
    {
      
        public RequestorsController()
            : base(new RequestorRepository(), new RequestorMapper())
        {

        }


        protected override void Initialize(RequestContext requestContext)
        {
            base.Initialize(requestContext);
            this.CheckSubscription();

            if (ViewBag.ViewCRM == false)
               Response.Redirect("/");
        }

        

        // GET: Suppliers
        public ActionResult Index(string ID)
        {
            if (ID != null) ViewBag.SupplierID = ID;

            return View();
        }

        public ActionResult Deleted()
        {
            if (ViewBag.DeleteCRM == false)
                Response.Redirect("/");

            return View();
        }



        #region Edit Requestor Panel

        // GET: /New Requestor
        public ActionResult _NewRequestor()
        {
            var requestor = new RequestorRepository().Read().OrderByDescending(x => x.RefID).FirstOrDefault();
            var refID = requestor != null ? requestor.RefID + 1 : 1;
            return PartialView(new RequestorViewModel() { RefID = refID });             
        }


        // POST: /New Requestor
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult _NewRequestor(RequestorViewModel viewModel)
        {
            if (viewModel == null) return RedirectToAction("Index");

            //Check to see if model is valid
            if (!ModelState.IsValid)
            {
                return PartialView(viewModel);
            }

            var model = _mapper.MapToModel(viewModel);
            _repo.Create(model);


            //Log Activity
            //AddLog(model.ID.ToString(), string.Format("{{{0}}} created.", 0), CurrentUser);
                
            return Json(new { ID = model.ID });                
           
        }



        // GET: /Edit Supplier
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")] 
        public ActionResult _EditRequestor(string ID)
        {
            try
            {
                //Make sure the supplier being returned belongs to the user of the user
                Requestor clt =  _repo.Read().Where(o => o.ID.ToString() == ID).First();
                RequestorViewModel model = _mapper.MapToViewModel(clt);

                ViewBag.CurrentUserID = CurrentUser.Id;
                ViewBag.CurrentUserEmail = CurrentUser.Email;
                return PartialView(model);
            }
            catch {
                return PartialView("_NewSupplier", new RequestorViewModel());
            }

        }


        // POST: /Edit Supplier
        [HttpPost]
        [ValidateAntiForgeryToken]
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")] 
        public ActionResult _EditRequestorDetails(RequestorViewModel viewModel)
        {
            if (viewModel == null) return RedirectToAction("Index");

            //Check to see if model is valid
            if (!ModelState.IsValid)
            {
                return PartialView(viewModel);
            }

            var edit = _repo.Find(Guid.Parse(viewModel.ID));
            _mapper.MapToModel(viewModel, edit);
            _repo.Update(edit);


            ViewBag.CurrentUserID = CurrentUser.Id;
            ViewBag.CurrentUserEmail = CurrentUser.Email;
            ViewBag.Saved = true; //Return a viewbag variable. Used to show message in front-end html.
            return PartialView(viewModel);
            
        }

        #endregion

    }
    
}

JMS/Views/Requestors/Index.cshtml
@{
    ViewBag.Title = "Requestor";
}

<div class="container">
    <div class="row">
        <div class="col-sm-6">
            <h1>Requestor</h1>
        </div>
        <div class="col-sm-6">
            <br />
            @*@if (ViewBag.EditCRM)
            {
                <div class="btn-group" style="float:right; margin-right:3px;">
                    <button type="button" class="btn btn-inverse dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span class="glyphicon glyphicon-cloud-upload"></span>&nbsp;Import <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu dropdown-menu-right">
                        <li><a href="@Url.Action("UploadRequestor", "RequestorImport")">Import Requestor, Addresses & Contacts</a></li>
                    </ul>
                </div>
            }            
            @if (ViewBag.DeleteCRM)
            {
                <a class="btn btn-danger" style="float:right; margin-right:3px;" href="/Requestor/Deleted/"><span class="glyphicon glyphicon-trash"></span> &nbsp;Deleted Requestor</a>
            }*@
        </div>
        <div class="col-sm-12">
            <br />
        </div>
        <div class="col-xs-6">
            @if (!User.IsInRole("Viewer"))
            {
                <a class="btn btn-inverse" onclick="NewRequestor()"><span class="glyphicon glyphicon-home"></span>&nbsp;New Requestor</a>
            }
        </div>
        <div class="col-xs-2">
            <br />
        </div>
        
        <div class="col-xs-4">
            <div class="input-group">
                @Html.TextBox("TB_RequestorFilter", null, new { @class = "form-control", @style = "max-width:none", @placeholder = "Search by Name" })
                <span class="input-group-btn">
                    <a class="btn btn-default" onclick="Refresh()"><span class="glyphicon glyphicon-search"></span></a>
                </span>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <hr />
        </div>
        <div id="divPager" class="col-sm-12">
             <div class="form-group" role="group" aria-label="...">
                <a class="btn btn-sm btn-default" onclick="Refresh()"><span class="glyphicon glyphicon-refresh" ></span>&nbsp; Refresh</a>&nbsp;
                 @if (ViewBag.EditCRM)
                 {
                    //<a class="btn btn-sm btn-default" onclick="Edit()"><span class="glyphicon glyphicon-edit"></span>&nbsp; Edit</a>
                 } 
            </div>
        </div>

        @if (ViewBag.EditCRM)
        {
            <div id="divEdit" class="col-sm-12" style="display:none">
                <div class="form-group" role="group" aria-label="...">
                    <a class="btn btn-sm btn-default" onclick="SelectAll()"><span class="glyphicon glyphicon-check"></span>&nbsp; Select All</a>&nbsp;
                    <a class="btn btn-sm btn-default" onclick="DeleteSelected()"><span class="glyphicon glyphicon-trash"></span>&nbsp; Delete Selected</a>&nbsp;
                    <a class="btn btn-sm btn-default" onclick="DoneEdit()"><span class="glyphicon glyphicon-ok"></span>&nbsp; Done</a>&nbsp;
                </div>
            </div>
        }
        <div class="col-sm-12">
            @(Html.Kendo().Grid<JMS.Models.RequestorViewModel>()
                .Name("GridRequestors")
                .HtmlAttributes(new { style = "min-width: 500px" })
                .Pageable(p => p.PageSizes(new[] { 50, 100, 200 }).Messages(m => m.Display("{0} - {1} of {2} Requestor").Empty("No Requestor Found")))
                .Columns(columns =>
                {
                    columns.Template(@<text></text>).ClientTemplate("<input type='checkbox' value='#=ID#' name='chk_grid'>").Width("1%").Hidden();
                    //columns.Bound(u => u.RefID).Title("ID").ClientTemplate("<a href='\\#' onclick='EditRequestor(\"#=ID#\"); return false;'><strong>#=RefID#</strong></a>").Width("1%");
                    columns.Bound(u => u.FirstName).Title("First Name").ClientTemplate("<a href='\\#' onclick='EditRequestor(\"#=ID#\"); return false;'><strong>#=FirstName#</strong></a>");
                    columns.Bound(u => u.Surname).Title("Surname").ClientTemplate("<a href='\\#' onclick='EditRequestor(\"#=ID#\"); return false;'><strong>#=Surname#</strong></a>");
                    columns.Template(@<text></text>).ClientTemplate("<a href='\\#' onclick='EditRequestor(\"#=ID#\"); return false;'><span class='glyphicon glyphicon-edit glyphicon-btn'/></a>").Width("1%");
                    columns.Command(command =>
                    {
                        command.Destroy().Text("<span class='glyphicon glyphicon-trash glyphicon-btn' title='Delete' />");
                    }).Visible(!User.IsInRole("Viewer")).Width("1%");
                })
                .Sortable()
                .Editable(editable => editable.ConfirmDelete("Are you sure you want to delete this Requestor?"))
                .DataSource(dataSource => dataSource
                    .Ajax()
                    .Model(model =>
                    {
                        model.Id(t => t.ID);
                    })
                    .Read(read => read.Action("Read", "RequestorGrid").Data("GetSearchInfo")).PageSize(50)
                    .Update(update => update.Action("Update", "RequestorGrid"))
                    .Destroy(destory => destory.Action("Destroy", "RequestorGrid"))
                    .Events(events => events.Error("KendoGridErrorHandler"))
                )
                .Events(events => events.DataBound("KendoGridDatabound"))
            )
        </div>        
    </div>
</div>


<a id="Button_Close_Content" class="btn btn-background" onclick="HideViews()" style="z-index:1105; display:none;"></a>

<div id="SlideContent_EditRequestor" class="panel panel-default" style="z-index: 1120; position: fixed; overflow-y:scroll; margin: 0; top: 0; bottom:0; right: 0%; min-height: 100%; width: 0; max-width: 1000px; display: none;">
    <div class="panel-body" style="margin-top: 10px;">
        <div id="EditRequestor_Body"></div>
    </div>
</div>

<script>

    @if (!string.IsNullOrEmpty(ViewBag.RequestorID))
    {
        <text>
    EditRequestor('@ViewBag.RequestorID');
    </text>
    }

    function Refresh() {
        var grid = $("#GridRequestors").data("kendoGrid");
        //if (grid.dataSource.page() != 1) {
        //    grid.dataSource.page(1);
        //}
        grid.dataSource.read();
    }

    function RefreshContacts() {
        var grid = $("#GridContactsSearch").data("kendoGrid");
        //if (grid.dataSource.page() != 1) {
        //    grid.dataSource.page(1);
        //}
        grid.dataSource.read();
    }

    function GetSearchInfo() {
        return {
            filterText: $('#TB_RequestorFilter').val(),
        }
    }

    function Edit() {
        var grid = $("#GridRequestors").data("kendoGrid");
        if (grid.dataSource.total() > 0) {
            $('#divPager').hide();
            $('#divEdit').show();
            grid.showColumn(0);
        }
    }

    function DoneEdit() {
        var grid = $("#GridRequestors").data("kendoGrid");
        $('#divPager').show();
        $('#divEdit').hide();
        grid.hideColumn(0);
    }

    function SelectAll() {
        if ($("input[name=chk_grid]:checkbox:checked").get().length > 0) {
            $("input[name=chk_grid]").map(function () { return this.checked = false; })
        }
        else {
            $("input[name=chk_grid]").map(function () { return this.checked = true; })
        }
    }


    $("#TB_RequestorFilter").keyup(function (e) {
        //if (e.keyCode == 13) {
            Refresh();
        //}
    });

    $("#TB_ContactFilter").keyup(function (e) {
        //if (e.keyCode == 13) {
            RefreshContacts();
        //}
    });


    //Below the following functions are used the show/hide the content panels.
    function NewRequestor() {
        $("#EditRequestor_Body").load("@Url.Action("_NewRequestor", "Requestors")");

        $("#SlideContent_EditRequestor").animate({ width: '90%' }, { queue: false, duration: 300 });
        $("#SlideContent_EditRequestor").fadeIn();
        $("#Button_Close_Content").fadeIn();
    }

    function EditRequestor(id) {
        var url = '@Url.Action("_EditRequestor", "Requestors")' + '?ID=' + id;
        $("#EditRequestor_Body").load(url);

        $("#SlideContent_EditRequestorTypes").fadeOut();
        $("#SlideContent_SearchContacts").fadeOut();

        $("#SlideContent_EditRequestor").animate({ width: '90%' }, { queue: false, duration: 300 });
        $("#SlideContent_EditRequestor").fadeIn();
        $("#Button_Close_Content").fadeIn();
    }

    function CreatedRequestor(id) {
        var url = '@Url.Action("_EditRequestor", "Requestors")' + '?ID=' + id;
        $("#EditRequestor_Body").load(url);
    }

    @if (ViewBag.EditCRM)
    {
        <text>

            function DeleteRequestor(id) {
                if (confirm("Are you sure you want to delete this organisation?")) {
                    $.ajax({
                        url: '@Url.Action("_DeleteRequestor", "Requestors")',
                        type: 'POST',
                        data: { "ID": id },
                        dataType: "json",
                        success: function (data) { Refresh(); }
                    });
                }
            }

            function DeleteSelected() {
                if (confirm("Are you sure you want to delete these organisations?")) {

                    var ids = $("input[name=chk_grid]:checkbox:checked").map(function () { return this.value; }).get().join();

                    $.ajax({
                        url: '@Url.Action("_DeleteRequestors", "RequestorGrid")',
                        type: 'POST',
                        data: { "IDs": ids },
                        dataType: "json",
                        success: function (data) { Refresh(); }
                    });
                }
            }
        </text>
    }

    function EditRequestorTypes() {

        $("#SlideContent_EditRequestorTypes").animate({ width: '90%' }, { queue: false, duration: 300 });
        $("#SlideContent_EditRequestorTypes").fadeIn();
        $("#Button_Close_Content").fadeIn();

        var grid = $("#GridAllLogs").data("kendoGrid");
        grid.dataSource.read();
    }


    function SearchContacts() {
        $("#SlideContent_SearchContacts").animate({ width: '90%' }, { queue: false, duration: 300 });
        $("#SlideContent_SearchContacts").fadeIn();
        $("#Button_Close_Content").fadeIn();

        var grid = $("#GridContactsSearch").data("kendoGrid");
        grid.dataSource.read();
    }

    function HideViews() {
        $("#SlideContent_EditRequestor").animate({ width: '0%' }, { queue: false, duration: 300 });
        $("#SlideContent_EditRequestorTypes").animate({ width: '0%' }, { queue: false, duration: 300 });
        $("#SlideContent_SearchContacts").animate({ width: '0%' }, { queue: false, duration: 300 });
        setTimeout(function () {
            $("#SlideContent_EditRequestor").fadeOut();
            $("#SlideContent_EditRequestorTypes").fadeOut();
            $("#SlideContent_SearchContacts").fadeOut();
            $("#Button_Close_Content").fadeOut();

            Refresh();
        }, 300);

    }


    @if (ViewBag.EditCRM)
    {
        <text>
    //ATTACHEMENT TAB FUNCTIONS
    function OnAttachmentUploadSuccess(e) {
        $('#GridAttachments').data('kendoGrid').dataSource.read();
    }

    function OnLinkAttactmentAdded(data) {
        $('#TB_AttachmentLink').val("");
        $('#GridAttachments').data('kendoGrid').dataSource.read();
    }


    function OnGridRequestorTypesRequestEnd(e) {
        //RequestEnd handler code
        if (e.type != 'read') {
            $("#DD_Types").data("kendoDropDownList").dataSource.read();
        }
    }
    </text>
    }


    @if (ViewBag.ExportCRM)
    {
        <text>

    function ExportRequestors() {
        var filterText = $('#TB_RequestorFilter').val();
        var type = $("#DD_Types").data("kendoDropDownList").value();

        var url = '@Url.Action("Export", "RequestorGrid")' + '?filterText=' + filterText + '&type=' + type;
        window.open(url, "_blank");
    }

    function ExportContacts() {
        var filterText = $('#TB_RequestorFilter').val();
        var type = $("#DD_Types").data("kendoDropDownList").value();

        var url = '@Url.Action("ExportContacts", "RequestorGrid")' + '?filterText=' + filterText + '&type=' + type;
        window.open(url, "_blank");
    }

    function ExportAddresses() {
        var filterText = $('#TB_RequestorFilter').val();
        var type = $("#DD_Types").data("kendoDropDownList").value();

        var url = '@Url.Action("ExportAddresses", "RequestorGrid")' + '?filterText=' + filterText + '&type=' + type;
        window.open(url, "_blank");
    }

    function ExportProducts() {
        var filterText = $('#TB_RequestorFilter').val();
        var type = $("#DD_Types").data("kendoDropDownList").value();

        var url = '@Url.Action("ExportProductsSupplied", "RequestorGrid")' + '?filterText=' + filterText + '&type=' + type;
        window.open(url, "_blank");
    }

    function ExportCategories() {
        var filterText = $('#TB_RequestorFilter').val();
        var type = $("#DD_Types").data("kendoDropDownList").value();

        var url = '@Url.Action("ExportCategoriesSupplied", "RequestorGrid")' + '?filterText=' + filterText + '&type=' + type;
        window.open(url, "_blank");
    }

    </text>
    }


</script>

JMS/Views/Requestors/_EditRequestor.cshtml
@model JMS.Models.RequestorViewModel

@Html.Partial("_EditRequestorDetails", Model)

<div class="row">
    <div class="col-sm-12">
        <br />
        @(Html.Kendo().TabStrip().Scrollable(false)
        .Name("Requestor_Tabstrip")
        .Items(tabstrip =>
        {
            tabstrip.Add().Text("Purchases").Content(@Html.Partial("_TabPurchases", Model).ToHtmlString()).Selected(true);
            tabstrip.Add().Text("Jobs").Content(@Html.Partial("_TabJobs", Model).ToHtmlString()).Selected(false);
            tabstrip.Add().Text("Equipments").Content(@Html.Partial("_TabEquipments", Model).ToHtmlString()).Selected(false);
            //tabstrip.Add().Text("Purchase Orders").Content(@Html.Partial("_PurchaseOrdersTab", Model).ToHtmlString()).Selected(false);
            /*
            if (Model.IsSupplier)
            {
                tabstrip.Add().Text("Supplier Categories").Content(@Html.Partial("_CategoriesTab", Model).ToHtmlString()).Selected(false);
            }
            */
        }))
    </div>
</div>

JMS/Views/Requestors/_EditRequestorDetails.cshtml
@model JMS.Models.RequestorViewModel

<div id="divEditRequestor">
     <script> $("divEditRequestor").submit(function (e) { e.preventDefault(e); }); </script>
    
    <div class="row form-table" style="margin-left:5px; margin-right:5px;">
        <div class="col-sm-12">
            @using (Ajax.BeginForm("_EditRequestorDetails", "Requestor", new AjaxOptions { UpdateTargetId = "divEditRequestor" }, FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                @Html.HiddenFor(model => model.ID)
                @Html.HiddenFor(model => model.RefID)
                <div id="div_Body" class="row">
                    <div class="col-xs-9">
                        <h2>Edit Requestor</h2>
                    </div>
                    <div class="col-xs-3">
                        <br />
                        <div style="float:right;">
                            @if (!User.IsInRole("Viewer"))
                            {
                            <input type="submit" value="Save Changes" class="btn btn-sm btn-inverse">
                            }
                            <a class="btn btn-sm btn-default" onclick="HideViews()"><span class="glyphicon glyphicon-remove"></span>&nbsp;Close</a>
                            @if (ViewBag.Saved != null)
                            {
                                <br />
                                <label class="l_Saved"><strong>Details Saved!</strong></label>
                            }
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <br />
                    </div>
                    <div class="col-sm-4">
                        <table>
                            @*<tr>
                                <td style="width:80px;"><label>ID:</label></td>
                                <td>
                                    @Html.TextBoxFor(model => model.RefID, new { @class = "form-control", @placeholder = "ID", @style = "max-width:none; width:100%;" })
                                    @Html.ValidationMessageFor(model => model.RefID, "", new { @class = "text-danger" })
                                </td>
                            </tr>*@
                            <tr>
                                <td><label>First Name:</label></td>
                                <td>
                                    @Html.TextBoxFor(model => model.FirstName, new { @class = "form-control", @placeholder = "First Name", @style = "max-width:none; width:100%;" })
                                    @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                                </td>
                            </tr>
                            <tr>
                                <td><label>Surname:</label></td>
                                <td>
                                    @Html.TextBoxFor(model => model.Surname, new { @class = "form-control", @placeholder = "Surname", @style = "max-width:none; width:100%;" })
                                    @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
                                </td>
                            </tr>
                        </table>
                    </div>
                    @if (!User.IsInRole("Viewer"))
                    {
                        <div class="col-sm-12">
                            <br /><br />
                            <input type="submit" value="Save Changes" class="btn btn-inverse">&nbsp;
                            @if (ViewBag.Saved != null)
                            {
                                <label class="l_Saved"><strong>Details Saved!</strong></label>
                                <script>
                                    setTimeout(function () { $(".l_Saved").fadeOut(); }, 2000);
                                </script>
                            }
                        </div>
                    }
                </div>
            }
        </div>
    </div>

</div>

JMS/Views/Requestors/_NewRequestor.cshtml
@model JMS.Models.RequestorViewModel

<div id="divNewOrg" style="margin:15px;">

    @using (Ajax.BeginForm("_NewRequestor", "Requestor", new AjaxOptions { UpdateTargetId = "divNewOrg", OnSuccess = "OnSuccess" }, FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        //@Html.ValidationSummary(false, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div id="div_Body"  class="row">
            <div class="col-xs-9">
                <h2>New Requestor</h2>
            </div>
            <div class="col-xs-3">
                <br />
                <div style="float:right;">
                    <input type="submit" value="Add Requestor" class="btn btn-sm btn-inverse">
                    <a class="btn btn-sm btn-default" onclick="HideViews()"><span class="glyphicon glyphicon-remove"></span>&nbsp;Close</a>
                </div>
            </div>
            <div class="col-sm-12">
                <br />
            </div>
            @Html.HiddenFor(model => model.RefID)
            <div class="col-sm-4">
                <table>
                    @*<tr>
                        <td style="width:80px;"><label>ID:</label></td>
                        <td>
                            @Html.TextBoxFor(model => model.RefID, new { @class = "form-control", @placeholder = "ID", @style = "max-width:none; width:100%;" })
                            @Html.ValidationMessageFor(model => model.RefID, "", new { @class = "text-danger" })
                        </td>
                    </tr>*@
                    <tr>
                        <td><label>First Name:</label></td>
                        <td>
                            @Html.TextBoxFor(model => model.FirstName, new { @class = "form-control", @placeholder = "First Name", @style = "max-width:none; width:100%;" })
                            @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                        </td>
                    </tr>
                    <tr>
                        <td><label>Surname:</label></td>
                        <td>
                            @Html.TextBoxFor(model => model.Surname, new { @class = "form-control", @placeholder = "Surname", @style = "max-width:none; width:100%;" })
                            @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
                        </td>
                    </tr>
                </table>
            </div>
            <div class="col-sm-4">
                <br />
            </div>
            <div class="col-sm-12">
                <br /><br />
                <input type="submit" value="Add Requestor" class="btn btn-inverse">
            </div>
        </div>
    }

    <script>
        function OnSuccess(response) {
            //Call function from Index view
            CreatedRequestor(response["ID"]);
        }
    </script>

    <style>
        #div_Body table tr th, #div_Body table tr td {
            padding: 2px;
        }

        #div_Body table {
            width: 100%;
        }
    </style>

</div>

JMS/Views/Requestors/_TabEquipments.cshtml
@model JMS.Models.RequestorViewModel

<br />

@(Html.Kendo().Grid<JMS.Models.EquipmentGridViewModel>()
              .Name("GridEquipments")
              .HtmlAttributes(new { style = "min-width: 900px" })
              .Pageable(p => p.PageSizes(new[] { 50, 100, 200 }).Messages(m => m.Display("{0} - {1} of {2} Equipments").Empty("No Equipments Found")))
              .Columns(columns =>
              {
                  columns.Bound(x => x.EquipNo).ClientTemplate("<a href='/Equipment/GoTo/#=ID#' target='_blank' title='Go to #=EquipNo#'>#=EquipNo#</a>");
                  columns.Bound(x => x.Title).ClientTemplate("<a href='/Equipment/GoTo/#=ID#' target='_blank' title='Go to #=EquipNo#'>#=Title#</a>");
                  columns.Bound(x => x.LocationName).Title("Location");
                  columns.Bound(x => x.DepartmentName).Title("Department").Encoded(false);
                  columns.Bound(u => u.ManufacturerID).Title("Manufacturer").ClientTemplate("#=Manufacturer#").Width("1%");
                  columns.Bound(u => u.EquipStatusID).Title("Status").ClientTemplate("<label class='label label-primary' style = 'background-color:#=EquipStatus.HexColour#;'>#=EquipStatus.Name#</label>").HtmlAttributes(new { @class = "div-inline" }).Width("1%").HeaderHtmlAttributes(new { @style = "text-align: center;" });
                  //columns.Template(@<text></text>).ClientTemplate("<a href='/Equipment/GoTo/#=ID#' target='_blank' title='Go to #=EquipNo#'><span class='glyphicon glyphicon-edit glyphicon-btn'/></a>").Width("1%");
              })
              //.Sortable()
              .DataSource(dataSource => dataSource
                  .Ajax()
                  .Model(model =>
                  {
                      model.Id(l => l.ID);
                  })
                  .Read(read => read.Action("Read", "EquipmentGrid", new { requestorID = Model.ID }).Data("function() { return { statuses: [1, 2, 3] } }")).PageSize(10)
              )
              .Events(events => events.DataBound("KendoGridDatabound"))

)